verison: 3.9
services:
   backend:
      build: backend
      ports:
        -"80:8080"
   frontend:
      build: frontend
      ports:
        -"5000:5000"
   flask-app:
      build: flask-app